### Accounts management examples

### accounts - create
POST http://localhost:8080/api/accounts
Content-Type: application/json

{
  "accountId": "9102",
  "owner": "Tom"
}

### accounts - deposit
POST http://localhost:8080/api/accounts/deposit
Content-Type: application/json

{
  "accountId": "9102",
  "amount": 200
}

### accounts - withdraw
POST http://localhost:8080/api/accounts/withdraw
Content-Type: application/json

{
  "accountId": "9102",
  "amount": 100
}

### accounts - balance
GET http://localhost:8080/api/accounts/9102/balance


### accounts - transactions
GET http://localhost:8080/api/accounts/9102/transactions
